version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tetekai-amla-weku-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tetekai_amla_weku
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
